# Data Preprocessing Notebook
#### This notebook implements data preprocessing on 3 main generated datasets. The final outputs of this notebook are `6 different preprocessed datasets.`
#### They are:
* `data18_sub_features_binary_classification` data, which is a preprocessed dataset from topology 1 that contains all selected features for binary classification.
* `data18_full_features_binary_classification` data, which is a preprocessed dataset from topology 1 that contains all the features for binary classification.
----------------------------------------------------------------------------------------------------------------------------------------------------
* `data50_sub_features_binary_classification` data, which is a preprocessed dataset from topology 2 that contains all selected features for binary classification.
* `data50_full_features_binary_classification` data, which is a preprocessed dataset from topology 2 that contains all the features for binary classification.
----------------------------------------------------------------------------------------------------------------------------------------------------
* `data100_sub_features_binary_classification` data, which is a preprocessed dataset from topology 3 that contains all selected features for binary classification.
* `data100_full_features_binary_classification` data, which is a preprocessed dataset from topology 3 that contains all the features for binary classification.

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("../data/data18.csv")
df.drop("timestamp", inplace = True, axis = 1) # Dropping timestamp Column
df.drop("Unnamed: 0", inplace = True, axis = 1) # Dropping Unnamed: 0 Column (if exists)
df

,datapath_id,flow_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,flow_duration_sec,...,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,4,2301,31,0,23,0,1,0,0,6,...,20,100,0,5,490,0.833333,1.118568e-08,8.166667e+01,1.096197e-06,0
1,3,23358546,1,5050,23,35854,6,-1,-1,6,...,20,100,0,91557,6042874,15259.500000,2.085581e-04,1.007146e+06,1.376509e-02,0
2,3,150506,23,35854,1,5050,6,-1,-1,6,...,20,100,0,399561,22775361578,66593.500000,8.465275e-04,3.795894e+09,4.825288e+01,0
3,3,3150501,23,35854,31,5050,1,0,8,6,...,20,100,0,6,564,1.000000,1.265823e-08,9.400000e+01,1.189873e-06,0
4,3,2350501,31,35854,23,5050,1,0,0,6,...,20,100,0,5,490,0.833333,1.128668e-08,8.166667e+01,1.106095e-06,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382124,2,19017,8,5126,19,0,17,-1,-1,14,...,20,100,0,13,2106,0.928571,1.409978e-08,1.504286e+02,2.284165e-06,1
1382125,2,19017,8,5281,19,0,17,-1,-1,14,...,20,100,0,5,810,0.357143,5.973716e-09,5.785714e+01,9.677419e-07,1
1382126,2,19017,8,22022,19,0,17,-1,-1,3,...,20,100,0,4,648,1.333333,5.115090e-09,2.160000e+02,8.286445e-07,1
1382127,2,19017,8,5027,19,0,17,-1,-1,15,...,20,100,0,17,2754,1.133333,3.090909e-07,1.836000e+02,5.007273e-05,1
1382128,2,19017,8,4738,19,0,17,-1,-1,15,...,20,100,0,18,2916,1.200000,2.319588e-08,1.944000e+02,3.757732e-06,1

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1382129 entries, 0 to 1382128
Data columns (total 21 columns):
 #   Column                    Non-Null Count    Dtype
---  ------                    --------------    -----
 0   datapath_id               1382129 non-null  int64
 1   flow_id                   1382129 non-null  int64
 2   ip_src                    1382129 non-null  int64
 3   tp_src                    1382129 non-null  int64
 4   ip_dst                    1382129 non-null  int64
 5   tp_dst                    1382129 non-null  int64
 6   ip_proto                  1382129 non-null  int64
 7   icmp_code                 1382129 non-null  int64
 8   icmp_type                 1382129 non-null  int64
 9   flow_duration_sec         1382129 non-null  int64
 10  flow_duration_nsec        1382129 non-null  int64
 11  idle_timeout              1382129 non-null  int64
 12  hard_timeout              1382129 non-null  int64
 13  flags                     1382129 non-null  int64
 14  packet_count              1382129 non-null  int64
 15  byte_count                1382129 non-null  int64
 16  packet_count_per_second   1382129 non-null  float64
 17  packet_count_per_nsecond  1382129 non-null  float64
 18  byte_count_per_second     1382129 non-null  float64
 19  byte_count_per_nsecond    1382129 non-null  float64
 20  label                     1382129 non-null  int64
dtypes: float64(4), int64(17)
memory usage: 221.4 MB

In [3]:
df

,datapath_id,flow_id,ip_src,tp_src,ip_dst,tp_dst,ip_proto,icmp_code,icmp_type,flow_duration_sec,...,idle_timeout,hard_timeout,flags,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond,label
0,4,2301,31,0,23,0,1,0,0,6,...,20,100,0,5,490,0.833333,1.118568e-08,8.166667e+01,1.096197e-06,0
1,3,23358546,1,5050,23,35854,6,-1,-1,6,...,20,100,0,91557,6042874,15259.500000,2.085581e-04,1.007146e+06,1.376509e-02,0
2,3,150506,23,35854,1,5050,6,-1,-1,6,...,20,100,0,399561,22775361578,66593.500000,8.465275e-04,3.795894e+09,4.825288e+01,0
3,3,3150501,23,35854,31,5050,1,0,8,6,...,20,100,0,6,564,1.000000,1.265823e-08,9.400000e+01,1.189873e-06,0
4,3,2350501,31,35854,23,5050,1,0,0,6,...,20,100,0,5,490,0.833333,1.128668e-08,8.166667e+01,1.106095e-06,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382124,2,19017,8,5126,19,0,17,-1,-1,14,...,20,100,0,13,2106,0.928571,1.409978e-08,1.504286e+02,2.284165e-06,1
1382125,2,19017,8,5281,19,0,17,-1,-1,14,...,20,100,0,5,810,0.357143,5.973716e-09,5.785714e+01,9.677419e-07,1
1382126,2,19017,8,22022,19,0,17,-1,-1,3,...,20,100,0,4,648,1.333333,5.115090e-09,2.160000e+02,8.286445e-07,1
1382127,2,19017,8,5027,19,0,17,-1,-1,15,...,20,100,0,17,2754,1.133333,3.090909e-07,1.836000e+02,5.007273e-05,1
1382128,2,19017,8,4738,19,0,17,-1,-1,15,...,20,100,0,18,2916,1.200000,2.319588e-08,1.944000e+02,3.757732e-06,1

# data18_sub_features_binary_classification

In [4]:
df = pd.read_csv("../data/data18.csv")
df18 = df.copy()

In [5]:
# We first define categorical and numerical features
cat_features = ["datapath_id", "ip_src", "ip_dst", "ip_proto", "icmp_code", "icmp_type", "flags"] # categorical features
num_features = ["flow_id", "tp_src", "tp_dst", "flow_duration_sec", "flow_duration_nsec", "idle_timeout", "hard_timeout", "packet_count", "byte_count", "packet_count_per_second", "packet_count_per_nsecond", "byte_count_per_second", "byte_count_per_nsecond"] #numerical features
number_of_features = len(cat_features) + len(num_features)

In [6]:
selected_features = ['datapath_id', # selected feature are specified in Recursive Feature Elimination Notebook
 'flow_id',
 'tp_src',
 'tp_dst',
 'ip_proto',
 'icmp_code',
 'icmp_type',
 'flow_duration_sec',
 'flow_duration_nsec',
 'idle_timeout',
 'packet_count',
 'byte_count',
 'packet_count_per_second',
 'packet_count_per_nsecond',
 'byte_count_per_second',
 'byte_count_per_nsecond']

In [7]:
# Min-Max Function
def min_max_normalize(column):
    min_val = column.min()
    max_val = column.max()
    column_normalized = (column - min_val) / (max_val - min_val)
    return column_normalized

In [8]:
x = pd.DataFrame() # a new empty dataframe. We will add preprocessed data into x dataframe. 

# We move forward Column by column to see which column is categorical or numerical.
for i in range(number_of_features):
    feature = df18.columns[i]
    if feature in cat_features and feature in selected_features:
        x = pd.concat([x, pd.get_dummies(df18[feature], prefix=feature, dtype='int8')],axis=1)
    elif feature in num_features and feature in selected_features:
        # Apply min-max normalization to the specified column
        x = pd.concat([x, min_max_normalize(df18[feature])],axis=1)
x

,datapath_id_1,datapath_id_2,datapath_id_3,datapath_id_4,datapath_id_5,flow_id,tp_src,tp_dst,ip_proto_1,ip_proto_6,...,icmp_type_0,icmp_type_3,icmp_type_8,flow_duration_sec,flow_duration_nsec,idle_timeout,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond
0,0,0,0,1,0,0.000004,0.000000,0.000000,1,0,...,1,0,0,0.06,0.447447,NaN,7.475427e-07,1.043540e-08,6.906390e-07,3.409512e-09
1,0,0,1,0,0,0.046155,0.077058,0.566128,0,1,...,0,0,0,0.06,0.439439,NaN,1.368855e-02,1.286934e-04,1.264657e-02,6.357067e-05
2,0,0,1,0,0,0.000297,0.547097,0.079739,0,1,...,0,0,0,0.06,0.472472,NaN,5.973778e-02,4.850407e-01,5.519048e-02,2.580304e-04
3,0,0,1,0,0,0.006225,0.547097,0.079739,1,0,...,0,0,1,0.06,0.474474,NaN,8.970513e-07,1.201136e-08,8.287668e-07,3.858359e-09
4,0,0,1,0,0,0.004644,0.547097,0.079739,1,0,...,1,0,0,0.06,0.443443,NaN,7.475427e-07,1.043540e-08,6.906390e-07,3.440298e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382124,0,1,0,0,0,0.000037,0.078218,0.000000,0,0,...,0,0,0,0.14,0.922923,NaN,1.943611e-06,4.485091e-08,7.695692e-07,4.297760e-09
1382125,0,1,0,0,0,0.000037,0.080583,0.000000,0,0,...,0,0,0,0.14,0.837838,NaN,7.475427e-07,1.725035e-08,2.959882e-07,1.820851e-09
1382126,0,1,0,0,0,0.000037,0.336034,0.000000,0,0,...,0,0,0,0.03,0.782783,NaN,5.980342e-07,1.380028e-08,1.105022e-06,1.559132e-09
1382127,0,1,0,0,0,0.000037,0.076707,0.000000,0,0,...,0,0,0,0.15,0.055055,NaN,2.541645e-06,5.865119e-08,9.392691e-07,9.421412e-08
1382128,0,1,0,0,0,0.000037,0.072297,0.000000,0,0,...,0,0,0,0.15,0.776777,NaN,2.691154e-06,6.210126e-08,9.945202e-07,7.070344e-09

In [9]:
x = pd.concat([x, df18["label"]], axis=1)
x.fillna(0, inplace=True)
x.to_csv("../data/preprocessed/data18_sub_features_binary_classification.csv", index=False)

# data18_full_features_binary_classification

In [10]:
df18 = df.copy()

In [11]:
x = pd.DataFrame() # a new empty dataframe. We will add preprocessed data into x dataframe. 

# We move forward Column by column to see which column is categorical or numerical.
for i in range(number_of_features):
    feature = df18.columns[i]
    if feature in cat_features:
        x = pd.concat([x, pd.get_dummies(df18[feature], prefix=feature, dtype='int8')],axis=1)
    else:
        # Apply min-max normalization to the specified column
        x = pd.concat([x, min_max_normalize(df18[feature])],axis=1)
x

,Unnamed: 0,timestamp,datapath_id_1,datapath_id_2,datapath_id_3,datapath_id_4,datapath_id_5,flow_id,ip_src_1,ip_src_2,...,icmp_type_8,flow_duration_sec,flow_duration_nsec,idle_timeout,hard_timeout,flags_0,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond
0,0.000000e+00,0.000000e+00,0,0,0,1,0,0.000004,0,0,...,0,0.06,0.447447,NaN,NaN,1,7.475427e-07,1.043540e-08,6.906390e-07,3.409512e-09
1,7.235220e-07,8.405514e-10,0,0,1,0,0,0.046155,1,0,...,0,0.06,0.439439,NaN,NaN,1,1.368855e-02,1.286934e-04,1.264657e-02,6.357067e-05
2,1.447044e-06,8.405514e-10,0,0,1,0,0,0.000297,0,0,...,0,0.06,0.472472,NaN,NaN,1,5.973778e-02,4.850407e-01,5.519048e-02,2.580304e-04
3,2.170566e-06,8.405514e-10,0,0,1,0,0,0.006225,0,0,...,1,0.06,0.474474,NaN,NaN,1,8.970513e-07,1.201136e-08,8.287668e-07,3.858359e-09
4,2.894088e-06,8.405514e-10,0,0,1,0,0,0.004644,0,0,...,0,0.06,0.443443,NaN,NaN,1,7.475427e-07,1.043540e-08,6.906390e-07,3.440298e-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382124,9.999971e-01,1.000000e+00,0,1,0,0,0,0.000037,0,0,...,0,0.14,0.922923,NaN,NaN,1,1.943611e-06,4.485091e-08,7.695692e-07,4.297760e-09
1382125,9.999978e-01,1.000000e+00,0,1,0,0,0,0.000037,0,0,...,0,0.14,0.837838,NaN,NaN,1,7.475427e-07,1.725035e-08,2.959882e-07,1.820851e-09
1382126,9.999986e-01,1.000000e+00,0,1,0,0,0,0.000037,0,0,...,0,0.03,0.782783,NaN,NaN,1,5.980342e-07,1.380028e-08,1.105022e-06,1.559132e-09
1382127,9.999993e-01,1.000000e+00,0,1,0,0,0,0.000037,0,0,...,0,0.15,0.055055,NaN,NaN,1,2.541645e-06,5.865119e-08,9.392691e-07,9.421412e-08
1382128,1.000000e+00,1.000000e+00,0,1,0,0,0,0.000037,0,0,...,0,0.15,0.776777,NaN,NaN,1,2.691154e-06,6.210126e-08,9.945202e-07,7.070344e-09

In [12]:
x = pd.concat([x, df18["label"]], axis=1)
x.fillna(0, inplace=True)
x = x.sample(frac=0.8)
x.to_csv("../data/preprocessed/data18_full_features_binary_classification.csv", index=False)

In [13]:
len(x.columns)

130

# data50_sub_features_binary_classification

In [14]:
df = pd.read_csv("../data/data50.csv")
df.drop("timestamp", inplace = True, axis = 1) # Dropping timestamp Column
df.drop("Unnamed: 0", inplace = True, axis = 1) # Dropping Unnamed: 0 Column.
df50 = df.copy()

In [15]:
x = pd.DataFrame() # a new empty dataframe. We will add preprocessed data into x dataframe. 

# We move forward Column by column to see which column is categorical or numerical.
for i in range(number_of_features):
    feature = df50.columns[i]
    if feature in cat_features and feature in selected_features:
        x = pd.concat([x, pd.get_dummies(df50[feature], prefix=feature, dtype='int8')],axis=1)
    elif feature in num_features and feature in selected_features:
        # Apply min-max normalization to the specified column
        x = pd.concat([x, min_max_normalize(df50[feature])],axis=1)
x

,datapath_id_1,datapath_id_2,datapath_id_3,datapath_id_4,datapath_id_5,datapath_id_6,flow_id,tp_src,tp_dst,ip_proto_1,...,icmp_type_8,flow_duration_sec,flow_duration_nsec,idle_timeout,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond
0,1,0,0,0,0,0,0.019035,0.077058,0.889308,0,...,0,0.04,0.480480,NaN,7.448038e-03,7.970546e-05,0.026278,1.542260e-04,1.093869e-04,1.783538e-07
1,1,0,0,0,0,0,0.000808,0.827741,0.082790,0,...,0,0.04,0.486486,NaN,3.070981e-02,2.814835e-01,0.108348,6.280553e-04,3.863048e-01,6.220886e-04
2,1,0,0,0,0,0,0.002958,0.827741,0.082790,1,...,1,0.04,0.484484,NaN,4.400527e-07,6.992509e-09,0.000002,9.036835e-09,9.596439e-09,1.551755e-11
3,1,0,0,0,0,0,0.001883,0.827741,0.082790,1,...,0,0.04,0.415415,NaN,4.400527e-07,6.992509e-09,0.000002,1.053935e-08,9.596439e-09,1.809758e-11
4,0,1,0,0,0,0,0.000002,0.000000,0.000000,1,...,1,0.04,0.423423,NaN,4.400527e-07,6.992509e-09,0.000002,1.034002e-08,9.596439e-09,1.775531e-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667518,0,0,0,1,0,0,0.000000,0.000000,0.000000,1,...,0,0.92,0.560561,NaN,1.334826e-05,2.121061e-07,0.000002,2.369157e-07,1.265617e-08,4.068184e-10
2667519,0,1,0,0,0,0,0.000005,0.000000,0.000000,1,...,1,0.92,0.563564,NaN,1.334826e-05,2.121061e-07,0.000002,2.356533e-07,1.265617e-08,4.046507e-10
2667520,0,1,0,0,0,0,0.000000,0.000000,0.000000,1,...,0,0.92,0.558559,NaN,1.334826e-05,2.121061e-07,0.000002,2.377649e-07,1.265617e-08,4.082766e-10
2667521,1,0,0,0,0,0,0.000005,0.000000,0.000000,1,...,1,0.92,0.565566,NaN,1.334826e-05,2.121061e-07,0.000002,2.348191e-07,1.265617e-08,4.032183e-10
2667522,1,0,0,0,0,0,0.000000,0.000000,0.000000,1,...,0,0.92,0.556557,NaN,1.334826e-05,2.121061e-07,0.000002,2.386201e-07,1.265617e-08,4.097452e-10

In [16]:
x = pd.concat([x, df50["label"]], axis=1)
x.fillna(0, inplace=True)
x.to_csv("../data/preprocessed/data50_sub_features_binary_classification.csv", index=False)

# data50_full_features_binary_classification

In [17]:
df50 = df.copy()

In [18]:
x = pd.DataFrame() # a new empty dataframe. We will add preprocessed data into x dataframe. 

# We move forward Column by column to see which column is categorical or numerical.
for i in range(number_of_features):
    feature = df50.columns[i]
    if feature in cat_features:
        x = pd.concat([x, pd.get_dummies(df50[feature], prefix=feature, dtype='int8')],axis=1)
    else:
        # Apply min-max normalization to the specified column
        x = pd.concat([x, min_max_normalize(df50[feature])],axis=1)
x

,datapath_id_1,datapath_id_2,datapath_id_3,datapath_id_4,datapath_id_5,datapath_id_6,flow_id,ip_src_0,ip_src_1,ip_src_2,...,flow_duration_nsec,idle_timeout,hard_timeout,flags_0,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond
0,1,0,0,0,0,0,0.019035,0,1,0,...,0.480480,NaN,NaN,1,7.448038e-03,7.970546e-05,0.026278,1.542260e-04,1.093869e-04,1.783538e-07
1,1,0,0,0,0,0,0.000808,0,0,0,...,0.486486,NaN,NaN,1,3.070981e-02,2.814835e-01,0.108348,6.280553e-04,3.863048e-01,6.220886e-04
2,1,0,0,0,0,0,0.002958,0,0,0,...,0.484484,NaN,NaN,1,4.400527e-07,6.992509e-09,0.000002,9.036835e-09,9.596439e-09,1.551755e-11
3,1,0,0,0,0,0,0.001883,0,0,0,...,0.415415,NaN,NaN,1,4.400527e-07,6.992509e-09,0.000002,1.053935e-08,9.596439e-09,1.809758e-11
4,0,1,0,0,0,0,0.000002,0,0,0,...,0.423423,NaN,NaN,1,4.400527e-07,6.992509e-09,0.000002,1.034002e-08,9.596439e-09,1.775531e-11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2667518,0,0,0,1,0,0,0.000000,0,0,0,...,0.560561,NaN,NaN,1,1.334826e-05,2.121061e-07,0.000002,2.369157e-07,1.265617e-08,4.068184e-10
2667519,0,1,0,0,0,0,0.000005,0,1,0,...,0.563564,NaN,NaN,1,1.334826e-05,2.121061e-07,0.000002,2.356533e-07,1.265617e-08,4.046507e-10
2667520,0,1,0,0,0,0,0.000000,0,0,0,...,0.558559,NaN,NaN,1,1.334826e-05,2.121061e-07,0.000002,2.377649e-07,1.265617e-08,4.082766e-10
2667521,1,0,0,0,0,0,0.000005,0,1,0,...,0.565566,NaN,NaN,1,1.334826e-05,2.121061e-07,0.000002,2.348191e-07,1.265617e-08,4.032183e-10
2667522,1,0,0,0,0,0,0.000000,0,0,0,...,0.556557,NaN,NaN,1,1.334826e-05,2.121061e-07,0.000002,2.386201e-07,1.265617e-08,4.097452e-10

In [19]:
x = pd.concat([x, df50["label"]], axis=1)
x.fillna(0, inplace=True)
x = x.sample(frac=0.6)
x.to_csv("../data/preprocessed/data50_full_features_binary_classification.csv", index=False)

# data100_sub_features_binary_classification

In [20]:
df = pd.read_csv("../data/data100.csv")
df.drop("timestamp", inplace = True, axis = 1) # Dropping timestamp Column
df.drop("Unnamed: 0", inplace = True, axis = 1) # Dropping Unnamed: 0 Column.
df100 = df.copy()

In [21]:
x = pd.DataFrame() # a new empty dataframe. We will add preprocessed data into x dataframe. 

# We move forward Column by column to see which column is categorical or numerical.
for i in range(number_of_features):
    feature = df100.columns[i]
    if feature in cat_features and feature in selected_features:
        x = pd.concat([x, pd.get_dummies(df100[feature], prefix=feature, dtype='int8')],axis=1)
    elif feature in num_features and feature in selected_features:
        # Apply min-max normalization to the specified column
        x = pd.concat([x, min_max_normalize(df100[feature])],axis=1)
x

,datapath_id_1,datapath_id_2,datapath_id_3,datapath_id_4,datapath_id_5,datapath_id_6,datapath_id_7,datapath_id_8,datapath_id_9,datapath_id_10,...,icmp_type_8,flow_duration_sec,flow_duration_nsec,idle_timeout,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond
0,0,0,0,0,1,0,0,0,0,0,...,0,0.00,0.335335,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,0,0,0,0,0,0,1,0,0,0,...,1,0.00,0.340340,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2,0,0,0,0,0,0,1,0,0,0,...,0,0.00,0.338338,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
3,1,0,0,0,0,0,0,0,0,0,...,0,0.00,0.443443,NaN,1.877614e-04,2.306869e-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,1,0,0,0,0,0,0,0,0,0,...,0,0.00,0.445445,NaN,2.635086e-04,7.326345e-05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4687925,1,0,0,0,0,0,0,0,0,0,...,0,0.06,0.418418,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4687926,1,0,0,0,0,0,0,0,0,0,...,0,0.10,0.852853,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4687927,1,0,0,0,0,0,0,0,0,0,...,0,0.13,0.825826,NaN,1.147686e-07,3.670268e-09,1.262054e-07,1.279809e-09,1.615056e-09,4.675442e-12
4687928,1,0,0,0,0,0,0,0,0,0,...,0,0.06,0.640641,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4687929,1,0,0,0,0,0,0,0,0,0,...,0,0.06,0.685686,NaN,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [22]:
x = pd.concat([x, df100["label"]], axis=1)
x.fillna(0, inplace=True)
x.to_csv("../data/preprocessed/data100_sub_features_binary_classification.csv", index=False)

# data100_full_features_binary_classification

In [23]:
df100 = df.copy()

In [24]:
x = pd.DataFrame() # a new empty dataframe. We will add preprocessed data into x dataframe. 

# We move forward Column by column to see which column is categorical or numerical.
for i in range(number_of_features):
    feature = df100.columns[i]
    if feature in cat_features:
        x = pd.concat([x, pd.get_dummies(df100[feature], prefix=feature, dtype='int8')],axis=1)
    else:
        # Apply min-max normalization to the specified column
        x = pd.concat([x, min_max_normalize(df100[feature])],axis=1)
x

,datapath_id_1,datapath_id_2,datapath_id_3,datapath_id_4,datapath_id_5,datapath_id_6,datapath_id_7,datapath_id_8,datapath_id_9,datapath_id_10,...,flow_duration_nsec,idle_timeout,hard_timeout,flags_0,packet_count,byte_count,packet_count_per_second,packet_count_per_nsecond,byte_count_per_second,byte_count_per_nsecond
0,0,0,0,0,1,0,0,0,0,0,...,0.335335,NaN,NaN,1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,0,0,0,0,0,0,1,0,0,0,...,0.340340,NaN,NaN,1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
2,0,0,0,0,0,0,1,0,0,0,...,0.338338,NaN,NaN,1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
3,1,0,0,0,0,0,0,0,0,0,...,0.443443,NaN,NaN,1,1.877614e-04,2.306869e-06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4,1,0,0,0,0,0,0,0,0,0,...,0.445445,NaN,NaN,1,2.635086e-04,7.326345e-05,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4687925,1,0,0,0,0,0,0,0,0,0,...,0.418418,NaN,NaN,1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4687926,1,0,0,0,0,0,0,0,0,0,...,0.852853,NaN,NaN,1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4687927,1,0,0,0,0,0,0,0,0,0,...,0.825826,NaN,NaN,1,1.147686e-07,3.670268e-09,1.262054e-07,1.279809e-09,1.615056e-09,4.675442e-12
4687928,1,0,0,0,0,0,0,0,0,0,...,0.640641,NaN,NaN,1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
4687929,1,0,0,0,0,0,0,0,0,0,...,0.685686,NaN,NaN,1,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00

In [25]:
x = pd.concat([x, df100["label"]], axis=1)
x.fillna(0, inplace=True)
x = x.sample(frac=0.4)
x.to_csv("../data/preprocessed/data100_full_features_binary_classification.csv", index=False)